// <auto-generated />
namespace Resturanto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Give_it_a_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Give_it_a_name));
        
        string IMigrationMetadata.Id
        {
            get { return "202101101751192_Give_it_a_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
